_parent_: configs/reconstruct/base.yaml


data:
  case: ct2wavy
  image_size: [2730,4096]
  frame_interval: 3
  conf_threshold: 0.4



ngp:
  marching_cubes_density_thresh: 2.8


PMVO:
  patch_size: 5

HairGenerate:
  connect_threshold: 0.0025
  grow_threshold: 0.8
  connect_dot_threshold: 0.8
  out_ratio: 0.1