_parent_: configs/reconstruct/base.yaml

prepare_data:
    fit_bust: true

bust_to_origin: [0.006, -1.644, 0.010]


data:
  case: ct2wings
  image_size: [2730,4096]
  frame_interval: 12
  conf_threshold: 0.4


PMVO:
   patch_size: 5
   conf_threshold: 0.1
   optimize: true

ngp:
  marching_cubes_density_thresh: 2.0


HairGenerate:
  connect_threshold: 0.005
  grow_threshold: 0.9
  connect_dot_threshold: 0.85
  out_ratio: 0.