_parent_: configs/Bust_fit/base.yaml

subject: ct2curly


savepath: data
subject_path: data/ct2curly
camera_path: data/ct2curly/ours/cam_params.json

data:
    image_size: [1920,1080]

smplx:
    n_shape: 300
    n_exp: 100



loss:
  scale_weight: 1