_parent_: configs/Bust_fit/base.yaml

subject: vcistefan


savepath: data
subject_path: data/vcistefan
camera_path: data/vcistefan/ours/cam_params.json

data:
    image_size: [1700,1400]

smplx:
    n_shape: 300
    n_exp: 100



loss:
  scale_weight: 1